-- sql/sampark_dashboard_view.sql
-- NOTE: This BigQuery view is preserved for reference.
-- The FREE stack uses DuckDB for analytics. Equivalent DuckDB queries
-- are defined in backend/main.py (dashboard endpoint) and
-- backend/tests/test_bq_performance.py.
--
-- This SQL is not actively used but documents the analytics schema
-- for migration or BigQuery deployment in the future.